/* Generated by re2c 0.16 on Sun Feb 19 17:23:34 2017 */
#line 1 "parse_pack.re"
/**
 * libamip -- Library with functions for read/create AMI packets
 * Copyright (C) 2016, Stas Kobzar <staskobzar@modulis.ca>
 *
 * This file is part of libamip.
 *
 * libamip is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * libamip is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with libamip.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file amip_parse.c
 * @brief AMI (Asterisk Management Interface) packet parser.
 *
 * @author Stas Kobzar <stas.kobzar@modulis.ca>
 */

#include <stdio.h>
#include <string.h>
#include "amip.h"

// introducing types:re2c for prompt packet

enum yycond_pack {
  yyckey,
  yycvalue,
};

AMIPacket *amiparse_pack (const char *pack_str)
{
  AMIPacket *pack = (AMIPacket*) malloc(sizeof(AMIPacket));
  amipack_init (pack, AMI_UNKNOWN);
  enum header_type hdr_type;
  const char *marker = pack_str;
  const char *cur    = marker;
  const char *ctxmarker;
  int c = yyckey;
  int len = 0;

  const char *tok = marker;


#line 56 "parse_pack.c"
{
	unsigned char yych;
	switch (c) {
	case yyckey: goto yyc_key;
	case yycvalue: goto yyc_value;
	}
/* *********************************** */
yyc_key:
	yych = *cur;
	switch (yych) {
	case '\r':	goto yy6;
	case ' ':	goto yy7;
	case ':':	goto yy9;
	case 'A':
	case 'a':	goto yy10;
	case 'E':
	case 'e':	goto yy11;
	case 'R':
	case 'r':	goto yy12;
	default:	goto yy3;
	}
yy3:
	++cur;
	yych = *cur;
yy4:
	switch (yych) {
	case ' ':
	case ':':	goto yy5;
	default:	goto yy3;
	}
yy5:
#line 92 "parse_pack.re"
	{
              len = cur - tok;
              hdr_type = HDR_UNKNOWN ;
              goto yyc_key;
            }
#line 94 "parse_pack.c"
yy6:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy13;
	default:	goto yy4;
	}
yy7:
	++cur;
yy8:
#line 70 "parse_pack.re"
	{ return NULL; }
#line 106 "parse_pack.c"
yy9:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy14;
	default:	goto yy8;
	}
yy10:
	yych = *++cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy16;
	default:	goto yy4;
	}
yy11:
	yych = *++cur;
	switch (yych) {
	case 'V':
	case 'v':	goto yy17;
	default:	goto yy4;
	}
yy12:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy18;
	default:	goto yy4;
	}
yy13:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy19;
	default:	goto yy4;
	}
yy14:
	++cur;
#line 73 "parse_pack.re"
	{ tok = cur; goto yyc_value; }
#line 144 "parse_pack.c"
yy16:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy20;
	default:	goto yy4;
	}
yy17:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy21;
	default:	goto yy4;
	}
yy18:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy22;
	default:	goto yy4;
	}
yy19:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy23;
	default:	goto yy4;
	}
yy20:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy25;
	default:	goto yy4;
	}
yy21:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy26;
	default:	goto yy4;
	}
yy22:
	yych = *++cur;
	switch (yych) {
	case 'P':
	case 'p':	goto yy27;
	default:	goto yy4;
	}
yy23:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy24;
	default:	goto yy3;
	}
yy24:
#line 71 "parse_pack.re"
	{ goto done; }
#line 203 "parse_pack.c"
yy25:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy28;
	default:	goto yy4;
	}
yy26:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy29;
	default:	goto yy4;
	}
yy27:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy31;
	default:	goto yy4;
	}
yy28:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy32;
	default:	goto yy4;
	}
yy29:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy30;
	default:	goto yy3;
	}
yy30:
#line 80 "parse_pack.re"
	{
              len = cur - tok;
              pack->type = AMI_EVENT;
              hdr_type = Event;
              goto yyc_key;
            }
#line 247 "parse_pack.c"
yy31:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy34;
	default:	goto yy4;
	}
yy32:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy33;
	default:	goto yy3;
	}
yy33:
#line 74 "parse_pack.re"
	{
              len = cur - tok;
              pack->type = AMI_ACTION;
              hdr_type = Action;
              goto yyc_key;
            }
#line 270 "parse_pack.c"
yy34:
	yych = *++cur;
	switch (yych) {
	case 'S':
	case 's':	goto yy35;
	default:	goto yy4;
	}
yy35:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy36;
	default:	goto yy4;
	}
yy36:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy37;
	default:	goto yy3;
	}
yy37:
#line 86 "parse_pack.re"
	{
              len = cur - tok;
              pack->type = AMI_RESPONSE;
              hdr_type = Response;
              goto yyc_key;
            }
#line 300 "parse_pack.c"
/* *********************************** */
yyc_value:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy43;
	case '\r':	goto yy45;
	default:	goto yy41;
	}
yy40:
#line 99 "parse_pack.re"
	{
              len = cur - tok;
              char *val = substr(tok, len, 0);
              amipack_append(pack, hdr_type, val);
              free (val);
              goto yyc_value;
            }
#line 318 "parse_pack.c"
yy41:
	++cur;
	yych = *cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy40;
	default:	goto yy41;
	}
yy43:
	++cur;
yy44:
#line 70 "parse_pack.re"
	{ return NULL; }
#line 332 "parse_pack.c"
yy45:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy46;
	default:	goto yy44;
	}
yy46:
	yych = *++cur;
	ctxmarker = cur;
	switch (yych) {
	case '\r':	goto yy48;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy49;
	default:	goto yy47;
	}
yy47:
	cur = marker;
	goto yy44;
yy48:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy51;
	default:	goto yy47;
	}
yy49:
	++cur;
	cur = ctxmarker;
#line 98 "parse_pack.re"
	{ tok = cur; goto yyc_key; }
#line 412 "parse_pack.c"
yy51:
	++cur;
#line 71 "parse_pack.re"
	{ goto done; }
#line 417 "parse_pack.c"
}
#line 107 "parse_pack.re"


done:
  return pack;
}
