/* Generated by re2c 0.16 on Sat Feb 18 11:06:19 2017 */
#line 1 "parse_pack.re"
/**
 * libamip -- Library with functions for read/create AMI packets
 * Copyright (C) 2016, Stas Kobzar <staskobzar@modulis.ca>
 *
 * This file is part of libamip.
 *
 * libamip is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * libamip is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with libamip.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file amip_parse.c
 * @brief AMI (Asterisk Management Interface) packet parser.
 *
 * @author Stas Kobzar <stas.kobzar@modulis.ca>
 */

#include <stdio.h>
#include <string.h>
#include "amip.h"

// introducing types:re2c for prompt packet

enum yycond_pack {
  yyckey,
  yycvalue,
};

int amiparse_pack (const char *pack_str,
                              AMIPacket *pack)
{
  enum pack_type rv = AMI_UNKNOWN;
  enum header_type hdr_type;
  const char *marker = pack_str;
  const char *cur = marker;
  const char *ctxmarker;
  int c = yyckey;
  int len = 0;

  const char *tok = marker;


#line 56 "parse_pack.c"
{
	unsigned char yych;
	switch (c) {
	case yyckey: goto yyc_key;
	case yycvalue: goto yyc_value;
	}
/* *********************************** */
yyc_key:
	yych = *cur;
	switch (yych) {
	case '\r':	goto yy6;
	case ' ':	goto yy7;
	case ':':	goto yy9;
	case 'A':
	case 'a':	goto yy10;
	case 'E':
	case 'e':	goto yy11;
	default:	goto yy3;
	}
yy3:
	++cur;
	yych = *cur;
yy4:
	switch (yych) {
	case ' ':
	case ':':	goto yy5;
	default:	goto yy3;
	}
yy5:
#line 87 "parse_pack.re"
	{ len = cur - tok;
                 hdr_type = HDR_UNKNOWN ;
                 goto yyc_key; }
#line 90 "parse_pack.c"
yy6:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy12;
	default:	goto yy4;
	}
yy7:
	++cur;
yy8:
#line 69 "parse_pack.re"
	{ return -1; }
#line 102 "parse_pack.c"
yy9:
	yych = *++cur;
	switch (yych) {
	case ' ':	goto yy13;
	default:	goto yy8;
	}
yy10:
	yych = *++cur;
	switch (yych) {
	case 'C':
	case 'c':	goto yy15;
	default:	goto yy4;
	}
yy11:
	yych = *++cur;
	switch (yych) {
	case 'V':
	case 'v':	goto yy16;
	default:	goto yy4;
	}
yy12:
	yych = *++cur;
	switch (yych) {
	case '\r':	goto yy17;
	default:	goto yy4;
	}
yy13:
	++cur;
#line 72 "parse_pack.re"
	{ tok = cur; goto yyc_value; }
#line 133 "parse_pack.c"
yy15:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy18;
	default:	goto yy4;
	}
yy16:
	yych = *++cur;
	switch (yych) {
	case 'E':
	case 'e':	goto yy19;
	default:	goto yy4;
	}
yy17:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy20;
	default:	goto yy4;
	}
yy18:
	yych = *++cur;
	switch (yych) {
	case 'I':
	case 'i':	goto yy22;
	default:	goto yy4;
	}
yy19:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy23;
	default:	goto yy4;
	}
yy20:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy21;
	default:	goto yy3;
	}
yy21:
#line 70 "parse_pack.re"
	{ goto done; }
#line 178 "parse_pack.c"
yy22:
	yych = *++cur;
	switch (yych) {
	case 'O':
	case 'o':	goto yy24;
	default:	goto yy4;
	}
yy23:
	yych = *++cur;
	switch (yych) {
	case 'T':
	case 't':	goto yy25;
	default:	goto yy4;
	}
yy24:
	yych = *++cur;
	switch (yych) {
	case 'N':
	case 'n':	goto yy27;
	default:	goto yy4;
	}
yy25:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy26;
	default:	goto yy3;
	}
yy26:
#line 80 "parse_pack.re"
	{
                  len = cur - tok;
                  pack->type = AMI_EVENT;
                  rv = AMI_EVENT;
                  hdr_type = Event;
                  goto yyc_key;
               }
#line 216 "parse_pack.c"
yy27:
	++cur;
	switch ((yych = *cur)) {
	case ' ':
	case ':':	goto yy28;
	default:	goto yy3;
	}
yy28:
#line 73 "parse_pack.re"
	{
                  len = cur - tok;
                  pack->type = AMI_ACTION;
                  rv = AMI_ACTION;
                  hdr_type = Action;
                  goto yyc_key;
               }
#line 233 "parse_pack.c"
/* *********************************** */
yyc_value:
	yych = *cur;
	switch (yych) {
	case '\n':	goto yy34;
	case '\r':	goto yy36;
	default:	goto yy32;
	}
yy31:
#line 92 "parse_pack.re"
	{
                      len = cur - tok;
                      char *val = substr(tok, len, 0);
                      amipack_append(pack, hdr_type, "CoreStatus");
                      free (val);
                      goto yyc_value;
                   }
#line 251 "parse_pack.c"
yy32:
	++cur;
	yych = *cur;
	switch (yych) {
	case '\n':
	case '\r':	goto yy31;
	default:	goto yy32;
	}
yy34:
	++cur;
yy35:
#line 69 "parse_pack.re"
	{ return -1; }
#line 265 "parse_pack.c"
yy36:
	yych = *(marker = ++cur);
	switch (yych) {
	case '\n':	goto yy37;
	default:	goto yy35;
	}
yy37:
	yych = *++cur;
	ctxmarker = cur;
	switch (yych) {
	case '\r':	goto yy39;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy40;
	default:	goto yy38;
	}
yy38:
	cur = marker;
	goto yy35;
yy39:
	yych = *++cur;
	switch (yych) {
	case '\n':	goto yy42;
	default:	goto yy38;
	}
yy40:
	++cur;
	cur = ctxmarker;
#line 91 "parse_pack.re"
	{ tok = cur;goto yyc_key; }
#line 345 "parse_pack.c"
yy42:
	++cur;
#line 70 "parse_pack.re"
	{ goto done; }
#line 350 "parse_pack.c"
}
#line 100 "parse_pack.re"


done:
  return rv;
}
